[package]
name = "dav"
version = "0.11.5"
edition = "2024"
resolver = "2"

[dependencies]
dav-proto = { path =  "/Users/me/code/dav-proto" }
common = { path = "../common" }
groupware = { path = "../groupware" }
directory = { path = "../directory" }
http_proto = { path = "../http-proto" }
trc = { path = "../trc" }
hashify = { version = "0.2" }
hyper = { version = "1.0.1", features = ["server", "http1", "http2"] }

[dev-dependencies]

[features]
test_mode = []
enterprise = []
